---
title: "About Us"
description: |
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# What? 

The purpose of the Data Science Lab's Research Consulting team is to give help and advice on methodological and technical issues that appear in the course of your research. We primarily focus on questions of research design, quantitative measurement and statistical inference, computational tools (particularly R and text analysis), and data visualization. 

We offer individual consultations and workshops for graduate students and researchers at the [Hertie School](https://www.hertie-school.org/en/) and the [SCRIPTS Cluster of Excellence](https://www.scripts-berlin.eu/). As of March 2020, we have been operating our consultations and workshops fully online. 

# Who? 

We are [Olga Gasparyan, PhD](mailto:o.gasparyan@hertie-school.org), [Dr. Will Lowe](mailto:lowe@hertie-school.org), [Allison Koh](mailto:koh@hertie-school.org), and [Lisa Oswald](mailto:l.oswald@phd.hertie-school.org). We particularly like to help with: 

-  __Olga__: Linear Models and data visualization in R (including maps), research design and causal inference, basic survey and experiments questions, data management in R and Python, basic Python questions, web scrapping in Python (including Selenium), Latex, basic ML consulting.  

- **Dr. Lowe**: Research design, causal inference, statistical modeling; data wrangling, visualization, text analysis (statistical or manual), GIS (maps), code optimization and parallel computing, all in R. Basic python consulting.

- **Allison**: Learning R and RStudio. Data wrangling, visualization, and working with text data in R and Python. Statistical computing in Stata.

- **Lisa**: Statistics in R, research design, data wrangling using R and Python, working with APIs / accessing data in Python, Network Analysis in Python, Agent based modelling in Netlogo, LaTeX

# How? 

### Consultations 

- If you are a student or researcher at the **Hertie School**, book an appointment on [Moodle](https://moodle.hertie-school.org/mod/scheduler/view.php?id=57896).  
- If you are a researcher with **SCRIPTS**, fill out the [consultation request form](https://forms.gle/uTUNPgW4UrZhRJVa9). 

### Workshops 

All graduate students, researchers, and affiliates of the Hertie School and the SCRIPTS Cluster of Excellence will be notified of upcoming workshops via email. 